### ISSUE TITLE
List stutters in the sample app

### ISSUE THREAD

**Issue by akhanalcs** [DIPSAS/DIPS.Mobile.UI#347]
I downloaded 'Components' app (great work btw) and was looking at Components and Resources in the app and noticed that the list at: 'Resources -> Sizes -> Sizes as font size' stutters very badly when scrolled.

Check out the video:

https://github.com/DIPSAS/DIPS.Mobile.UI/assets/30603497/8c0470bf-709e-477c-b9c5-1d0420782adc

**Comment by haavamoa** [comment]
Hello @akhanalcs , thank you for having a look at our samples app. We will definitely have a look at this stuttering list, we do think its related to this issue with .NET MAUI:
https://github.com/dotnet/maui/issues/19383
